apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: microprofile-app
spec:
  replicas: 1
  selector:
    app: microprofile-app
  template:
    metadata:
      labels:
        app: microprofile-app
    spec:
      containers:
      - name: nginx-image
        #change the image name
        image: docker.io/ishangulhane/nginx-server
        ports:
        - containerPort: 80
        env:
          - name: SOURCE_IP
           #change the value of IP with Kubernetes EXTERNAL-IP
            value: xx.xx.xx.xx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: microprofile-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
    protocol: TCP
    name: http
  selector:
    app: microprofile-app
  type : NodePort
