apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-vote-sample
  labels:
    app: microprofile-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vote-deployment
    spec:
      containers:
      - name: microservice-vote
        #change the image name
        image: journeycode/microservice-ol-vote
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
          - name: dbUsername
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbUsername
          - name: dbPassword
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbPassword
          - name: dbUrl
            value: http://cloudant-service:80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: microprofile-app
spec:
  clusterIP: None
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    name: vote-deployment
